#!/bin/bash
mkdir -p /opt/runc-demo/oci
cp -R /image/oci/* /opt/runc-demo/oci/
cp  /image/runcdemo.service /etc/systemd/system/

/usr/bin/nsenter -m/proc/1/ns/mnt systemctl enable runcdemo.service -i
/usr/bin/nsenter -m/proc/1/ns/mnt systemctl start runcdemo.service -i
