apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: runc-demo
  namespace: kube-system
  labels:
    k8s-app: runc
spec:
  selector:
    matchLabels:
      name: runc-demo
  template:
    metadata:
      labels:
        name: runc-demo
    spec:
      containers:
      - name: runc-demo
        image: jgriffith/runc-demo
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: proc
          mountPath: /proc
        - name: bin
          mountPath: /usr/bin
        - name: opt
          mountPath: /opt
        - name: systemd
          mountPath: /etc/systemd/system
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dev
        hostPath:
          path: /dev
      - name: proc
        hostPath:
          path: /proc
      - name: bin
        hostPath:
          path: /usr/bin
      - name: opt
        hostPath:
          path: /opt
      - name: systemd
        hostPath:
          path: /etc/systemd/system
