#!/bin/bash
cd /opt/runc-demo/oci

case $1 in
start)
  /opt/runc-demo/oci/demo-runc run -d demo
;;
stop)
  /opt/runc-demo/oci/demo-runc kill demo KILL
  sleep 2
  /opt/runc-demo/oci/demo-runc delete demo
;;
restart)
  /opt/runc-demo/oci/demo-runc kill demo KILL
  /opt/runc-demo/oci/demo-runc delete demo
  /opt/runc-demo/oci/demo-runc run -d demo
;;
esac
